### ISSUE TITLE
Implement Testable for Fn* instead?

### ISSUE THREAD

**Issue by nagisa** [BurntSushi/quickcheck#161] opened 2017-02-26 13:34 UTC
Currently Testable is implemented for function pointers, but there’s no reason (is there?) it couldn’t be implemented for `Fn` and `FnMut` (also abstracting over the fn pointer implementations).

**Comment by BurntSushi** [comment] 2017-02-26 13:38
@nagisa I've tried and failed several times. This issue specifically is a dupe of #56, which is blocked on https://github.com/rust-lang/rust/issues/25041. Judging by the labeling, it sounds like there are no bugs, so this may never happen based on the path I was following at least.

I welcome others to attack this problem.

**Closed** 2017-11-28 21:12 UTC
