### ISSUE TITLE
Add Arbitrary implementation for small arrays

### ISSUE THREAD

**Issue by tbu-** [BurntSushi/quickcheck#92] opened 2015-09-10 20:42 UTC
<strike>Alternatively implement `Arbitrary` for all arrays using the `FixedSizeArray` trait from the standard library (requires nightly).</strike> (see below).

**Comment by tomjakubowski** [comment] 2015-09-10 21:04
Isn't Arbitrary limited to a single implementation for "T" subject to some bounds (to avoid overlapping instances)?

**Comment by tbu-** [comment] 2015-09-10 22:32
Yea, you're right, the second version doesn't work.

**Comment by BurntSushi** [comment] 2016-01-27 21:47
Are there any concrete use cases for this? Could we get away with only adding impls for a few? I'm hesistant to add a bunch of impls if they increase compile times and aren't holding their weight.

**Comment by tbu-** [comment] 2016-01-27 22:24
I currently generate arrays of bytes to test that my serialize/deserialize roundtrips.

**Comment by cyplo** [comment] 2018-12-23 09:54
This would be extremely useful for small byte arrays for me as well, functions that I test typically have `[u8; 32]` as an argument type, not necessarily even a slice but a known size array.

**Comment by BurntSushi** [comment] 2020-01-11 02:18
I'm going to call this a duplicate of #187. We've held out this long. I suppose we can hold out a little longer for const generics to land.

**Closed by BurntSushi** 2020-01-11 02:18 UTC
Labels: duplicate

**Comment by JulianKnodt** [comment] 2024-10-12 06:32
I know this issue is already closed, and I can open a separate issue, but is it worth revisiting this with min const generics more widely available? Was working on QR decomposition, and was hoping to use quickcheck to validate my implementation.


https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html
